name: Build and Deploy linebot to Cloud Run
on:
  push:
    branches:
      - main
    paths:
      - packages/common/**
      - packages/linebot/**

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPPOSITY }}/${{ secrets.GCP_IMAGE }}:${{ github.sha }}
          push: true

      - name: Deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPPOSITY }}/${{ secrets.GCP_IMAGE }}:${{ github.sha }}
          service: ${{ secrets.GCP_CLOUD_RUN_SERVICE }}
          secrets: |
            CHANNEL_ACCESS_TOKEN=CHANNEL_ACCESS_TOKEN:latest
            CHANNEL_SECRET=CHANNEL_SECRET:latest
            DATABASE_URL=DATABASE_URL:latest
          region: asia-northeast1
